version: 0.2

env:
  secrets-manager:
    ECR_URL: "arn:aws:secretsmanager:us-east-2:579193032838:secret:test-demo-xgGHri:ECR_URL"
    ECR_REPOSITORY_NAME: "arn:aws:secretsmanager:us-east-2:579193032838:secret:test-demo-xgGHri:ECR_REPOSITORY_NAME"
    ECR_URI: "arn:aws:secretsmanager:us-east-2:579193032838:secret:test-demo-xgGHri:ECR_URI"
    IMAGE_TAG: "arn:aws:secretsmanager:us-east-2:579193032838:secret:test-demo-xgGHri:IMAGE_TAG"
  variables:
    BRANCH_NAME: $BRANCH_NAME

phases:
  pre_build:
    commands:
      - echo "Current branch $BRANCH_NAME"
      - echo "Starting pre-build..."
      # Build the Spring Boot application JAR file using Maven
      - mvn clean package -DskipTests

      - echo "Logging to Docker Hub..."
      - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD

      - echo "Logging to AWS ECR"
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_URL
  build:
    commands:
      - echo "Building Docker image..."
      - |
        if [ "$BRANCH_NAME" == "dev" ]; then
          echo "Building with Dockerfile.dev"
          docker build -f Dockerfile.dev -t $ECR_REPOSITORY_NAME .
        else
          echo "The environment is not dev"
        fi
  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - |
        if [ "$BRANCH_NAME" == "dev" ]; then
          echo "Pushing the image with dev repository"
          docker tag $ECR_REPOSITORY_NAME:$IMAGE_TAG $ECR_URI:$IMAGE_TAG
          docker push $ECR_URI:$IMAGE_TAG
        else
          echo "The environment is not dev"
        fi
artifacts:
  files:
    - target/demo-sprint-boot-0.0.1-SNAPSHOT.jar
    - imagedefinitions.json # Include the imagedefinitions file as artifact