# Use an OpenJDK base image
FROM adoptopenjdk/openjdk11:alpine

# Install bash, useful for debugging
RUN apk add --no-cache bash

# Set the working directory inside the container
WORKDIR /app

# Copy the application JAR file from the working directory
ARG JAR_FILE=target/data-collector-service-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} app.jar

# Expose the port where the Spring Boot application will run
EXPOSE 8021

# Command to run Spring Boot application
CMD ["java", "-jar", "app.jar"]

